# Site settings
title: eran.ws
subtitle: portfolio
email: eranws@gmail.com
email_href: "mailto:eranws@gmail.com?Subject=Hi Eran, this is <your%20name>"

description: ""
baseurl: "" # /forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Eran Weissenstern
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/eranws/
gitlab_url:
googleplus_url: #https://plus.google.com/u/0/+
linkedin_url: https://il.linkedin.com/pub/eran-weissenstern/61/154/936/ #https://www.linkedin.com/in/
pinterest_url:
slack_url:
twitter_url: #https://twitter.com/
stackoverflow_url: https://stackoverflow.com/users/648298/eran-w?tab=profile`

# Build settings
markdown: kramdown

sass:
  style: compressed
